/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wilsonflying_testjni_AccessNative */

#ifndef _Included_com_wilsonflying_testjni_AccessNative
#define _Included_com_wilsonflying_testjni_AccessNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wilsonflying_testjni_AccessNative
 * Method:    readStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wilsonflying_testjni_AccessNative_readStringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_wilsonflying_testjni_AccessNative
 * Method:    putStringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wilsonflying_testjni_AccessNative_putStringFromJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wilsonflying_testjni_AccessNative
 * Method:    getSum
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_com_wilsonflying_testjni_AccessNative_getSum
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_wilsonflying_testjni_AccessNative
 * Method:    callBackVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wilsonflying_testjni_AccessNative_callBackVoid
  (JNIEnv *, jobject);

/*
 * Class:     com_wilsonflying_testjni_AccessNative
 * Method:    GetMemVar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wilsonflying_testjni_AccessNative_GetMemVar
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
