//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.wilsonflying.testannotation;

import android.content.Context;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class MyService_
    extends MyService
{


    public static MyService_.IntentBuilder_ intent(Context context) {
        return new MyService_.IntentBuilder_(context);
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<MyService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, MyService_.class);
        }

    }

}
